/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Rectangle;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module RetangleTest in RetangleTest.asn1 */
	&asn_DEF_Rectangle,	
	0
};

